# Generated by Django 4.1.8 on 2023-04-21 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_blogpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPage",
        ),
    ]
